### ISSUE TITLE
Add Windows High Contrast Mode detection

### ISSUE THREAD

**Issue by ZoeBijl** [MichielBijl/font-awesome#6]
We need this for test two: visually hidden text.

See [Karl Groves' fiddle with Hans Hillen's code](http://jsfiddle.net/karlgroves/XR8Su/6/).

**Comment by mitchellevan** [comment]
I can imagine some potential reasons to detect high contrast mode, related to icons. But how does this detection relate to test two specifically? Would we make it part of the coding technique, or part of the testing procedure?

**Comment by mitchellevan** [comment]
Now I've read the discussion here:
https://github.com/FortAwesome/Font-Awesome/issues/6133

... and I agree with this point from @hanshillen:

> Font icons are actually Windows High Contrast Mode safe, because HC Mode does not override the icon's font-family (just the color and size). However, the issue Karl describes does occur for user defined stylesheets, which are likely to do exactly that: override font-family for all elements, causing the font based icons to break.

So I conclude you should discard issue #6.

I've added issue #20 for font customization.

**Comment by ZoeBijl** [comment]
Yeah, I should've included a more descriptive text; because I forgot why I thought we needed this. Closing now :)
